version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo:latest
    command: sh /mongo-seed/import.sh
    volumes:
      - ./mongo-seed:/mongo-seed
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
